### ISSUE TITLE
Cleaning actual transcriptions produces the same output as cleaning expected transcriptions.

### ISSUE THREAD

**Issue by KatieProchilo** [Joll59/d-ser-t#40]
**Description:**
* The expected transcription currently:
   * is lowercase.
   * contains apostrophes in words that are contractions.
   * replaces "okay" with "ok".
   * replaces hyphens with a space.
   * errors out if any other special characters are present.
   * allows digits (which we may want to change since we expect lexical responses from the STT service).

**Acceptance criteria:**
* Determine what special characters are returned from the STT service, and identify any patterns.
* Account for these patterns when cleaning the actual transcription.
* The actual transcription should match the expected transcription. Right now it:
   * is lowercase.
   * is lexical (e.g. the number 2 is returned as "two").

**Comment by KatieProchilo** [comment]
@HobbyProjects this is first on my list to get to today - I know this is of interest to you. I'll add in whatever oddities you've found so far, but let me know if there are new ones.

**Comment by HobbyProjects** [comment]
Sure, here is a list i've seen so far (without duplicates). Full list is here: https://dev.azure.com.rproxy.goskope.com/tkerchev/RAMSAY/_build/results?buildId=124

`Result: Already so that's a suivie egg bites. Ham cheddar and peppers anything else for you.
Expected: "alrighty so that's a sous vide egg bites ham cheddar and peppers anything else for you"`

`Result: Sure, thing, so I've added a cinnamon almondmilk macchiato anything else today.
Expected: "sure thing so i've added a cinnamon almondmilk macchiato anything else today"`

`Result: Sure, thing, so that they cinnamon Dolce Latte anything else.
Expected: "sure thing so that's a cinnamon dolce latte anything else"`

`Result: Hi. Thank you for choosing Starbucks what can I get started for you this morning?
Expected: "hi thank you for choosing starbucks what can i get started for you this morning"`

`Result: OK, so I've gotten eggs and cheese protein box anything else today.
Expected: "okay so i've got an eggs and cheese protein box anything else today"`

`Result: OK, so I've added a Michelle at Augustine Lemon Ridge anything else.
Expected: "okay so i've added a michel et augustin lemon meringue anything else"`

'Result: OK so adding milk chocolate mocha anything else.
Expected: "okay so i'll add a milk chocolate mocha anything else"`

`Result: OK so adding oh forgot to start anything else today.
Expected: "okay so i'll add an affogato strato anything else today"`

`Result: Sure, thing, so I've added a Berry prickly are pear frappuccino blended creme anything else for you.
Expected: "sure thing so i've added a berry prickly pear frappuccino blended creme anything else for you"`

`Result: Sure, thing, so I've added it birthday cake cream frappuccino anything else today.
Expected: "sure thing so i've added a birthday cake creme frappuccino anything else today"`

` Result: Alrighty so I've got a Blonde Cafe Americano, anything else.
Expected: "alrighty so i've got a blonde caffe americano anything else"`

`Result: Already so I've added a blonde vanilla latte anything else today.
Expected: "alrighty so i've added a blonde vanilla latte anything else today"`

`Result: OK, so I have added a caramel Brule frappuccino blended beverage anything else today.
Expected: "okay so i've added a caramel brulee frappuccino blended beverage anything else today"`

`Result: Sure, thing, so at a caramel frappuccino blended beverage anything else for you.
Expected: "sure thing so i'll add a caramel frappuccino blended beverage anything else for you"`

`Result: Sure, thing, so add a caramel light frappuccino blended coffee anything else.
Expected: "sure thing so i'll add a caramel light frappuccino blended coffee anything else"`

`Result: Sure, thing, so that they caramel waffle cone. Creme frappuccino blended creme anything else today.
Expected: "sure thing so that's a caramel waffle cone creme frappuccino blended creme anything else today"`

`Result: Alrighty so I've got a caramel ised, honey cream anything else.
Expected: "alrighty so i've got a caramelized honey creme anything else"`

`Result: Alrighty so add a chicken sausage rap anything else.
Expected: "alrighty so i'll add a chicken sausage wrap anything else"`

`Result: OK, so I've added a Chestnut pray lean chai tea latte anything else.
Expected: "okay so i've added a chestnut praline chai tea latte anything else"`
